import type { Metadata } from "next";
import localFont from "next/font/local";
import dynamic from "next/dynamic";
import { SignalRProvider } from '@/lib/signalrcontext';
const ReduxProvider = dynamic(() => import("./StoreProvider"), {
  ssr: false
});
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <SignalRProvider>
            <main className="grid h-screen overflow-auto space-y-0">
              {children}
            </main>
          </SignalRProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
